### ISSUE TITLE
Failed to activate the tab-move-key package

### ISSUE THREAD

**Issue by nathancarter** [malko/atom-tab-move-key#1]
1. Launch Atom with several tabs open.
2. Press Alt-PgDn in one tab, to try to move it later in the tab list.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [tab-move-key](https://github.com/malko/atom-tab-move-key) package, v0.1.0
### Stack Trace

Failed to activate the tab-move-key package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/nathan/.atom/packages/tab-move-key/lib/tab-move-key.coffee:4:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)
```
### Commands

```
     -0:00.8.0 tab-move-key:right (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "Zen",
      "spell-check",
      "autocomplete-css",
      "autocomplete-html",
      "autocomplete-plus",
      "autocomplete-snippets",
      "markdown-preview"
    ],
    "themes": [
      "one-dark-ui",
      "wombat"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.9
atom-runner, v2.4.1
auto-update-packages, v1.0.0
build, v0.40.0
color-picker, v2.0.7
file-icons, v1.5.8
markdown-preview-plus, v1.5.0
mathjax-wrapper, v0.1.0
minimap, v4.10.2
tab-move-key, v0.1.0
travis-ci-status, v0.15.1
wombat, v1.0.4

# Dev
No dev packages
```

**Comment by malko** [comment]
This package is not maintained anymore as moving tabs around is now part of atom as default feature.
Here's the keybindings names to lookup in atom keybindings settings: 

pane:show-previous-item
pane:show-next-item
pane:move-item-right
pane:move-item-left
